package viewer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ekstrak.java
 *
 * Created on Apr 23, 2013, 6:46:58 PM
 */


import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import metode.DekripRGB;
import metode.classsisipke;

/**
 *
 * @author angga cahyo
 */
public class Ekstrak extends javax.swing.JFrame {

    JFileChooser jf = new JFileChooser();
    String alamatgambardwt;
    BufferedImage gmbr2;

    DekripRGB drgb=new DekripRGB();
    classsisipke cd=new classsisipke();

    /** Creates new form Ekstrak */
    public Ekstrak() {
        initComponents();
        txtpesan.setEditable(false);
    }

    private void dapatkangambardariurl(String url) {
        File fil = new File(url);
        try {
            gmbr2 = ImageIO.read(fil);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "file tidak didapatkan");
        }
    }

    public BufferedImage loadimage(String url) {
        BufferedImage bmg = null;
        try {
            bmg = ImageIO.read(new File(url));
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "");
        }
        return bmg;
    }

    public BufferedImage resize(BufferedImage img, int newW, int newH) {
        int wi = img.getWidth();
        int he = img.getHeight();

        BufferedImage bim = new BufferedImage(newW, newH, img.getType());

        Graphics2D gp = bim.createGraphics();
        gp.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        gp.drawImage(img, 0, 0, newW, newH, 0, 0, wi, he, null);
        gp.dispose();
        return bim;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblgambaresktrak = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnekstrak = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpesan = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gambar"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblgambaresktrak, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblgambaresktrak, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Cari Gambar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnekstrak.setText("Ekstrak Gambar");
        btnekstrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnekstrakActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Ekstrak"));

        txtpesan.setColumns(20);
        txtpesan.setRows(5);
        jScrollPane1.setViewportView(txtpesan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnekstrak)
                                .addGap(14, 14, 14)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnekstrak)
                    .addComponent(jButton2))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter ff2 = new FileNameExtensionFilter(".bmp",".JPG","PNG", "bmp","JPG","PNG");
        jf.setFileFilter(ff2);
        int l = jf.showOpenDialog(null);
        if (l == jf.APPROVE_OPTION) {

            alamatgambardwt = jf.getSelectedFile().getPath();//mendapatkan url gambar dari pemilihan Jfile chooser
            dapatkangambardariurl(alamatgambardwt);
//            namaFile = jf.getName();//mendapatkan nama file dari URL
//            System.out.print(namaFile);

            BufferedImage igmbr = loadimage(alamatgambardwt);

            int pn = igmbr.getHeight();//mengetahui panjang gambar
            int lb = igmbr.getWidth();//mengetahui lebar gambar

            if (pn <= 200 || lb < 200) {
                JOptionPane.showMessageDialog(null, " masukkan gambar minimal ukuran 200 X 200 Px","ERROR",JOptionPane.ERROR_MESSAGE);
                //reset();
            } else if (pn > 1024 || lb > 1024) {
                JOptionPane.showMessageDialog(null, " masukkan gambar maximal ukuran 1024 X 1024 Px","ERROR",JOptionPane.ERROR_MESSAGE);
                //reset();
            } else if( pn != lb){
                JOptionPane.showMessageDialog(null, "anda harus memasukkan gambar dalam ukuran persegi","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {

                ImageIcon imii = new ImageIcon(resize(igmbr, lblgambaresktrak.getWidth(), lblgambaresktrak.getHeight()));
                lblgambaresktrak.setIcon(imii);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnekstrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnekstrakActionPerformed
        // TODO add your handling code here:


        BufferedImage gmbaryangakandiekstrak = loadimage(alamatgambardwt);
        //BufferedImage gmbar=mbtgmbr.setGambarintrgb(gmbaryangakandiekstrak);

        if (gmbaryangakandiekstrak == null) {

            JOptionPane.showMessageDialog(null, "maaf tidak ada gambar untuk di eksekusi");

        } else {

            //System.out.println("sukses");

           
            int[] bitberisipesan=drgb.Memasukkanrgbtobitpesan(gmbaryangakandiekstrak);
            byte[] pesan=cd.ekstrak_teks(bitberisipesan);
            String isipesan=new String(pesan);
            txtpesan.setText(isipesan);
            
        }





    }//GEN-LAST:event_btnekstrakActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();

        int x = (int) ((posisi.getWidth() - this.getWidth()) / 2);
        int y = (int) ((posisi.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        alamatgambardwt=null;
        lblgambaresktrak.setIcon(new ImageIcon());
        gmbr2=null;
        txtpesan.setText("");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menuUtm mnt=new menuUtm();
        mnt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ekstrak().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnekstrak;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblgambaresktrak;
    private javax.swing.JTextArea txtpesan;
    // End of variables declaration//GEN-END:variables
}
